1. Write a function, foo_1, that takes a NumPy array `arr` and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’

In [1]:
import numpy as np

In [8]:
def foo_1(a, target):
    y = abs(target - a)
    if target in a:
        print(np.argsort(y))
    else:
        print('no item found')
    

In [13]:
foo_1(np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10]), 11)

no item found


2. Write a user defined function foo_2 that takes a  2,3 dim NumPy array arr and returns a new n-1 dim array, where each element is replaced by the count of non-zero elements wrt axis.

In [ ]:
arr1 = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]])

In [39]:
def foo_2(a):
    counter = 0
    for i in a:
        if i!=0:
            counter+=1
    return counter

[2 2 2 1]
[4 1 2]


In [40]:
print(np.apply_along_axis(foo_2, axis = 0, arr = arr1))

[2 2 2 1]


In [41]:
print(np.apply_along_axis(foo_2, axis = 1, arr = arr1))

[4 1 2]


In [43]:
arr2 = np.array([[[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]],

                [[2, 0, 1, 0],
                 [0, 5, 0, 0],
                 [1, 2, 3, 4]]])


In [44]:
print(np.apply_along_axis(foo_2, axis = 0, arr = arr2))

[[2 1 2 1]
 [0 2 0 0]
 [2 1 2 1]]


In [45]:
print(np.apply_along_axis(foo_2, axis = 1, arr = arr2))

[[2 2 2 1]
 [2 2 2 1]]


In [46]:
print(np.apply_along_axis(foo_2, axis = 2, arr = arr2))

[[4 1 2]
 [2 1 4]]


3.1 You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array.

In [47]:
array1 = np.array([[85, 89, 88],
                  [78, 89, 94],
                  [91, 87, 90],
                  [87, 95, 84]])

In [62]:
def foo_3(a):
    x = np.where(a > 90)[0]
    if len(x) > 0:
        print(a, end="\n\n")

In [65]:
x = np.apply_along_axis(foo_3, axis=1, arr=array1)

[78 89 94]

[91 87 90]

[87 95 84]



3.2 You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales.

In [75]:
a = np.array([[120, 150, 130, 110],
              [200, 180, 220, 250],
              [90, 100, 95, 110],
              [300, 280, 320, 340]])

In [72]:
prodA = a[0]
print('Mean of product A',np.mean(prodA))
print('Median of product A',np.median(prodA))
print('Standard deviation of product A',np.std(prodA))
print('Highest sale',np.max(prodA))

Mean of product A 127.5
Median of product A 125.0
Standard deviation of product A 14.79019945774904
Highest sale 150


In [91]:
def clculate(a):
    counter=1
    for i in a:
        print(f'Mean of product {counter} : {np.mean(i)}')
        print(f'Median of product {counter}: {np.median(i)}')
        print(f'Standard deviation of product {counter}: {np.std(i)}')
        print(f'Highest sale {counter}: {np.max(i)}')
        print(end='\n\n')
        counter+=1

In [92]:
clculate(a)

Mean of product 1 : 127.5
Median of product 1: 125.0
Standard deviation of product 1: 14.79019945774904
Highest sale 1: 150


Mean of product 2 : 212.5
Median of product 2: 210.0
Standard deviation of product 2: 25.8602010819715
Highest sale 2: 250


Mean of product 3 : 98.75
Median of product 3: 97.5
Standard deviation of product 3: 7.39509972887452
Highest sale 3: 110


Mean of product 4 : 310.0
Median of product 4: 310.0
Standard deviation of product 4: 22.360679774997898
Highest sale 4: 340




3.3 Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.

In [166]:
A = np.random.randint(1,100,1000)

In [167]:
np.sort(A)[::-1]
v, c = np.unique(A, return_counts=True)
v, c

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
        69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
        86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([10,  8, 10,  8,  9, 11,  9, 13, 10, 13, 13, 14,  9,  5, 11, 11, 11,
         7,  6, 15,  7,  8, 12,  9,  9, 13,  9, 12,  6, 13, 13,  9,  8, 15,
         8,  7,  9, 10, 11, 14, 10,  9, 16, 16,  9,  5,  7, 13, 13, 16, 11,
         8, 11, 14,  7, 15,  9, 15,  8,  9,  9,  9,  8,  9,  7,  9, 12, 11,
         7, 11,  6, 11, 15, 10,  9,  9,  4,  7,  6,  9,  9, 10,  6, 12, 10,
        14,  8,  7,  9, 10, 11, 11, 11,  8, 16,  8, 12, 12, 12]))

In [168]:
x = np.argsort(-c)
x

array([49, 94, 42, 43, 33, 19, 57, 55, 72, 11, 39, 53, 85, 47, 29, 30, 25,
       48, 10,  9,  7, 83, 97, 27, 96, 66, 98, 22, 52, 50, 92, 91, 90, 14,
       15, 16,  5, 38, 71, 69, 67, 73,  0, 40, 37,  8, 84, 89,  2, 81, 65,
       63,  6, 75, 26, 79, 80,  4, 88, 74, 61, 24, 59, 23, 31, 36, 60, 44,
       41, 56, 12,  1, 95, 93, 58, 32, 21, 34, 86,  3, 62, 51, 20, 46, 64,
       54, 87, 17, 35, 68, 77, 18, 78, 28, 82, 70, 45, 13, 76])

In [169]:
for i in x[:10]:
    print(f'{v[i]} occures {c[i]} times')

50 occures 16 times
95 occures 16 times
43 occures 16 times
44 occures 16 times
34 occures 15 times
20 occures 15 times
58 occures 15 times
56 occures 15 times
73 occures 15 times
12 occures 14 times
